# https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-registry-proxy
  namespace: default
  labels:
    k8s-app: kube-registry-proxy
    kubernetes.io/cluster-service: "true"
    version: v0.4
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-registry-proxy
        kubernetes.io/name: "docker-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: fabric8-docker-registry.default.svc.cluster.local
        - name: REGISTRY_PORT
          value: "80"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000